# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171015_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
