# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_map_init_ai_infos'),
        ('api', '0004_map_stage'),
    ]

    operations = [
    ]
