# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20171102_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='final_dir',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='init_dir',
            field=models.IntegerField(default=16),
        ),
    ]
