# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171102_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='failed_msg',
            field=models.TextField(blank=True, default='再加把劲！'),
        ),
        migrations.AddField(
            model_name='map',
            name='passed_msg',
            field=models.TextField(blank=True, default='厉害了！'),
        ),
        migrations.AddField(
            model_name='map',
            name='std_blockly_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='welcome_msg',
            field=models.TextField(blank=True, default='无。'),
        ),
    ]
