# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='final_dir',
        ),
        migrations.RemoveField(
            model_name='map',
            name='final_ground_boxes',
        ),
        migrations.RemoveField(
            model_name='map',
            name='final_ground_colors',
        ),
        migrations.RemoveField(
            model_name='map',
            name='final_hand_boxes',
        ),
        migrations.RemoveField(
            model_name='map',
            name='init_ground_boxes',
        ),
        migrations.RemoveField(
            model_name='map',
            name='init_hand_boxes',
        ),
        migrations.RemoveField(
            model_name='map',
            name='n_max_hand_boxes',
        ),
        migrations.AddField(
            model_name='map',
            name='final_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='init_attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='map',
            name='init_hp',
            field=models.IntegerField(default=10),
        ),
    ]
