# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171122_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='init_ground_colors',
        ),
    ]
