# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_map_init_ground_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
