# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_solution_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
