# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_solution_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
