# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 08:08
from __future__ import unicode_literals

from django.db import migrations

def set_admin_share(apps, schema_editor):
    Map = apps.get_model('api', 'Map')
    for map_obj in Map.objects.all():
        map_obj.shared = map_obj.author.id == 1
        map_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_map_shared'),
    ]

    operations = [
        migrations.RunPython(set_admin_share),
    ]
